### ISSUE TITLE
[Improvement] Add required dependencies for different platforms/distros 

### ISSUE THREAD

**Issue by qtdyn** [fasterthanlime/troubleshoot-ftl#1]
`troubleshoot-ftl.sh: line 14: ping6: command not found` :(

**Comment by fasterthanlime** [comment]
> `troubleshoot-ftl.sh: line 14: ping6: command not found` :(

Which system is this? The script runs on macOS latest & Debian 12 at least.

You can probably edit it to use `ping -6` instead.

**Comment by qtdyn** [comment]
This was on ArchLinux. There's also the `aur/iputils-ping6-symlink` package which ~~might be~~ is overkill but gets the job done.

**Comment by fasterthanlime** [comment]
I pushed an update that detects whether to use `ping6` or `ping -6`, does it work for you? 

(https://github.com/fasterthanlime/troubleshoot-ftl/commit/3354dadf14c17af57da684646a92e88023a5d400)

**Comment by qtdyn** [comment]
Yup, script works great! Thanks :)

Also since I'm here, [here's my output](https://gist.github.com/xtrm-en/c9f2ad497dcb396b64c49d1ec312a82b) (since I also can't access your website).

love your content, take care of yourself :)
